### ISSUE TITLE
PoW How, Who, When, Will It Be Done

### ISSUE THREAD

**Issue by Copenman** [NeuCoin/neucoin#1]
I was curious as to the hows, whose, whats, whens, and wheres of the PoW aspect? While we have received the algorithm that will be utilized we still have not received any type of answer as to how the coins and by who the coins are being mined for PoW, (at least no post I've been able to find). That being said and launch approaching any answers would be greatly appreciated and would allow many open threads around this to be closed, @Sandrine @Darteous @ophelie @James would greatly appreciate any information you can give.

Thanks Again,

Copenman

**Comment by opheliekimie** [comment]
Hi Copenman,

This is a place to report issues with the client. I am therefore closing this issue. 
Also, I believe Sandrine has already replied to your question on the forum.

**Comment by Copenman** [comment]
Thanks Ophelie much appreciated.
