### ISSUE TITLE
Estimated Staking Time?

### ISSUE THREAD

**Issue by mb2140** [NeuCoin/neucoin#12]
Is it possible to add an estimate staking time based on network weight and your current coin age?  I've been staking since yesterday and have not minted anything yet.  Great job by the way!

**Comment by arcanis** [comment]
That would be an interesting feature. Remember tho that your coins have to sit still for at least 1.6 days before being able to stake.

**Comment by arcanis** [comment]
Good news, this feature has been implemented as of 4add8a8917ec6dd11e667d3fc0b7265482b526e1 :)
