### ISSUE TITLE
Neucoin running on Rpi2

### ISSUE THREAD

**Issue by ghost** [NeuCoin/neucoin#14]
is it possible to cross compile the source code for ARM?

**Comment by ghost** [comment]
https://github.com/NeuCoin/neucoin/blob/master/doc/compile-debian.md
would the directions from this also work on raspbian?

**Comment by Magicking** [comment]
Yes certainly, you may have to double check the version of libdb to 5.3, a
different version could break cross compatibility of .dat files including
_wallet.dat_

**Comment by ghost** [comment]
i followed the debian compile instructions and got the following error:
pi@raspberrypi ~/Desktop/neucoin-1.0.0/src $ make -f Makefile.unix neucoin-qt
uic -o qt/forms/ui_aboutdialog.h qt/forms/aboutdialog.ui
make: Circular qt/bitcoin.qrc <- qt/bitcoin.qrc.cpp dependency dropped.
lrelease -qm qt/locale/bitcoin_fr_FR.qm qt/locale/bitcoin_fr_FR.ts
g++ -c -o version.cpp.o version.cpp -W -Wall -Wno-unused-parameter -I /home/pi/Desktop/neucoin-1.0.0/src/qt/forms -I /home/pi/Desktop/neucoin-1.0.0/src/qt -I /home/pi/Desktop/neucoin-1.0.0/src -DHAVE_BUILD_INFO -fPIE -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets  
version.cpp:32:23: fatal error: build.h: No such file or directory
compilation terminated.
Makefile.common:78: recipe for target 'version.cpp.o' failed
make: **\* [version.cpp.o] Error 1

**Comment by Magicking** [comment]
The file build.h should be generated automatically when you start the build process.

You can bypass the generation by creating an empty file "build.h" with `touch build.h` in the src directory.

**Comment by ghost** [comment]
i added the build file and the binaries build without error but now the QT client build generates this error: 
 -I /home/pi/Desktop/neucoin-1.0.0/src/qt/forms -I /home/pi/Desktop/neucoin-1.0.0/src/qt -I /home/pi/Desktop/neucoin-1.0.0/src -DHAVE_BUILD_INFO -fPIE -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets  
qt/aboutdialog.cpp:2:28: fatal error: ui_aboutdialog.h: No such file or directory
compilation terminated.
Makefile.common:78: recipe for target 'qt/aboutdialog.cpp.o' failed
make: **\* [qt/aboutdialog.cpp.o] Error 1

**Comment by nemecis1000** [comment]
I personally would love to see that focused on the raspberry pi 1 mb 256 so as to be super-efficient

**Comment by arcanis** [comment]
@mitch42 There's probably something wrong in the way you've installed Qt5 - the `ui_*.h` files are automatically generated, so if they're missing it can only mean that Qt failed to generated them.

That being said, I'm not familiar with the Raspberry devices, but do you really want the Qt client for such a device? The headless client should work just fine. In such a case, you can just use the `NO_QT=1` when building to avoid the Qt dependency:

```
$> make -f Makefile.unix NO_QT=1
```

Closing for now, unless you've got further inquiries.
