### ISSUE TITLE
Compiling on non debian distros

### ISSUE THREAD

**Issue by arosboro** [NeuCoin/neucoin#15]
Can you provide some instructions on using qmake etc to get this to compile on non debian systems such as gentoo.

I've installed qt5 but am getting errors like the following:

```
#error "cannot be used with the include files from this version of Qt."
  ^
qt/./addresstablemodel.moc:15:2: error: #error "(The moc has changed too much.)"
 #error "(The moc has changed too much.)"
```

**Comment by arcanis** [comment]
I'm not familiar with the Gentoo package manager. You should only have to find the right ones and everything should go smoothly with a simple `make -f Makefile.unix`, as stated in the Debian documentation.

According to your log, it seems your system has some kind of conflict between Qt4 and Qt5, so I suggest you double check this.

Closing as not-a-bug, but feel free to comment later if you manage to find the right packages.

**Comment by arosboro** [comment]
Thanks arcanis.

I looked into this.  Here are the steps I took to compile.  Note: I followed https://wiki.gentoo.org/wiki/Qt/Qt5 to get Qt5 on my system.  The other libraries were already installed.

`which moc` shows `/usr/bin/moc`, and `/usr/bin/moc -> qtchooser`.  So to use qt5 I need to edit Makefile.common and add `-qt=5` to `MOC ?= moc` so that it looks like `MOC ?= moc -qt=5`

I also get 

> fatal error: db_cxx.h: No such file or directory
> #include <db_cxx.h>

Which can be resolved ala https://github.com/dogecoin/dogecoin/issues/76#issuecomment-31350943 by adding `-I/usr/include/db4.8` to the end of CXXFLAGS in src/Makefile.default

You may need to run make -f Makefile.common clean before building make -f Makefile.unix neucoin-qt

I had to replace QtGUI with Qt Widgets in ui_aboutdialog.h

```
#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QVBoxLayout>
```

```
sed -i -- 's/include <QtGui/include <QtWidgets/g' qt/forms/*.h
```

UnicodeUTF8’ is not a member of ‘QApplication’ error:

```
sed -i -- 's/, QApplication::UnicodeUTF8//g' qt/forms/*.h
```

If you get qrencode.h: No such file or directory, you'll need to install media-gfx/qrencode.

Send a tip to NXoVVUB3tf4GzCXXfnD78kNgj4YtnpuPZC  if you found this useful ;)
