### ISSUE TITLE
Problem Compiling Windows Dependencies

### ISSUE THREAD

**Issue by Copenman** [NeuCoin/neucoin#18]
Hello

I am receiving the following when attempting to compile the windows dependencies:

Joelseph@CopenmanHP /c/dependencies
$ compile-dependencies.sh
Microsoft Windows [Version 10.0.10240](c) 2015 Microsoft Corporation. All rights reserved.

c:\Dependencies\qttools-opensource-src-5.4.2>  set INCLUDE=c:\Dependencies\.\libpng\libpng-1.6.18\;c:\Dependencies\.\openssl\openssl-1.0.1m\\include

c:\Dependencies\qttools-opensource-src-5.4.2>  set LIB=c:\Dependencies\.\libpng\libpng-1.6.18\\.libs;c:\Dependencies\.\openssl\openssl-1.0.1m\\include

c:\Dependencies\qttools-opensource-src-5.4.2>  set PATH=%PATH%;c:\Dependencies\.\qtbase-opensource-src-5.4.2\\bin

c:\Dependencies\qttools-opensource-src-5.4.2>  qmake -makefile qttools.pro
Qt: Untested Windows version 10.0 detected!

c:\Dependencies\qttools-opensource-src-5.4.2>  mingw32-make
cd src/ && ( test -e Makefile || c:/Dependencies/qtbase-opensource-src-5.4.2/bin/qmake.exe C:/Dependencies/qttools-opensource-src-5.4.2/src/src.pro -o Makefile ) && mingw32-make -f Makefile
mingw32-make[1]: Entering directory 'c:/Dependencies/qttools-opensource-src-5.4.2/src'
cd linguist/ && ( test -e Makefile || c:/Dependencies/qtbase-opensource-src-5.4.2/bin/qmake.exe C:/Dependencies/qttools-opensource-src-5.4.2/src/linguist/linguist.pro -o Makefile ) && c:/Dependencies/mingw32/bin/mingw32-make -f Makefile
mingw32-make[2]: Entering directory 'c:/Dependencies/qttools-opensource-src-5.4.2/src/linguist'
cd lrelease/ && ( test -e Makefile || c:/Dependencies/qtbase-opensource-src-5.4.2/bin/qmake.exe C:/Dependencies/qttools-opensource-src-5.4.2/src/linguist/lrelease/lrelease.pro -o Makefile ) && c:/Dependencies/mingw32/bin/mingw32-make -f Makefile
Qt: Untested Windows version 10.0 detected!
Project ERROR: Unknown module(s) in QT: core-private xml
Makefile:40: recipe for target 'sub-lrelease-make_first' failed
mingw32-make[2]: **\* [sub-lrelease-make_first] Error 3
mingw32-make[2]: Leaving directory 'c:/Dependencies/qttools-opensource-src-5.4.2/src/linguist'
Makefile:40: recipe for target 'sub-linguist-make_first' failed
mingw32-make[1]: **\* [sub-linguist-make_first] Error 2
mingw32-make[1]: Leaving directory 'c:/Dependencies/qttools-opensource-src-5.4.2/src'
makefile:40: recipe for target 'sub-src-make_first' failed
mingw32-make: **\* [sub-src-make_first] Error 2

On the following system:

OS Name Microsoft Windows 10 Home
Version 10.0.10240 Build 10240
Other OS Description    Not Available
OS Manufacturer Microsoft Corporation
System Name COPENMANHP
System Manufacturer Hewlett-Packard
System Model    HP ENVY m7 Notebook PC
System Type x64-based PC
System SKU  J9K05UA#ABA
Processor   Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz, 2401 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date   Insyde F.51, 7/20/2015
SMBIOS Version  2.7
Embedded Controller Version 78.33
BIOS Mode   UEFI
BaseBoard Manufacturer  Hewlett-Packard
BaseBoard Model Not Available
BaseBoard Name  Base Board
Platform Role   Mobile
Secure Boot State   On
PCR7 Configuration  Binding Not Possible
Windows Directory   C:\WINDOWS
System Directory    C:\WINDOWS\system32
Boot Device \Device\HarddiskVolume2
Locale  United States
Hardware Abstraction Layer  Version = "10.0.10240.16392"
User Name   CopenmanHP\Joelseph
Time Zone   Pacific Daylight Time
Installed Physical Memory (RAM) 12.0 GB
Total Physical Memory   11.9 GB
Available Physical Memory   5.98 GB
Total Virtual Memory    15.0 GB
Available Virtual Memory    7.58 GB
Page File Space 3.10 GB
Page File   C:\pagefile.sys
Hyper-V - VM Monitor Mode Extensions    Yes
Hyper-V - Second Level Address Translation Extensions   Yes
Hyper-V - Virtualization Enabled in Firmware    No
Hyper-V - Data Execution Protection Yes

**Comment by arcanis** [comment]
> Qt: Untested Windows version 10.0 detected!
> Project ERROR: Unknown module(s) in QT: core-private xml

Apparently your Qt installation is missing two required Qt modules.

Closing as not-a-bug.

**Comment by Copenman** [comment]
lol and those would be obtained how?  As i followed the windows compile doc https://github.com/NeuCoin/neucoin/blob/master/doc/compile-windows.md and downloaded qtbase-opensource-src-5.4.2 as it instructs so this and is now about the 5th thing that I've had to fix in the compile-dependencies.sh is it perhaps only meant to be compiled on 32b systems?  Also this is a bug in the documentation for performing the windows compile, if the compile only works with one architecture that would be a bug correct

**Comment by arcanis** [comment]
Our builds have all been made on a 64bits architecture (a fresh unmodified Windows 8.1), so that's unlikely to be the issue.

**Comment by Copenman** [comment]
But I'm also using Windows 10 could that be an issue?

**Comment by arcanis** [comment]
Well, Qt is telling you the following:

> Qt: Untested Windows version 10.0 detected!

So yep, I guess it might have something to do with this :) As far as I know, Qt 5.5 should have the Windows 10 support, but we haven't checked this. The official way to build the software is to use a virtual machine (so that nothing tampers the build, and the build doesn't tamper your own environment), so you could just as well use a Windows 8.1 machine.

**Comment by Copenman** [comment]
Ok thanks

**Comment by Copenman** [comment]
```
                1/14: $20 to you!
















































                Hi there,
                Joelseph wants to let you in on Schoola, and we think you’re going to love it. Gently used clothes at up to 90% off. $2 of every $5 goes to save subjects like art and music in our classrooms. And $20 free to get you started.

                A note from Joelseph:

                    I was on Schoola and thought you might like it. Amazing savings on quality clothes and 40% funds school programs for our kids. Use my link and get $20 free!


                 Shop with Joelseph’s special link, and you’ll get an instant $20 credit. Make a purchase, and Joelseph gets a $20 credit of her own. It pays to share, right?!


                 These credits expire after 60 days, so don’t dilly dally.









                                SHOP NOW AND GET $20







                <3 your new pals at Schoola

































































                    To ensure delivery to your inbox, add updates@schoola.com to your
                        address book.
                    © 2016 Schoola, 601 Montgomery Street, Suite 675  San Francisco, CA 94111This message was sent to: reply@reply.github.com
                    Thank you for reading. We really appreciate it! :)








 

Click here to unsubscribe.
```
