### ISSUE TITLE
Missing qmake

### ISSUE THREAD

**Issue by JERisBRISK** [NeuCoin/neucoin#21]
I'm still trying to get the client to compile by following the directions step-by-step. (Largely because I want to try out the redfish fork that shows minting info).

The main issue I've had with the how-to doc (neucoin/doc/compile-windows.md) is that it suggests you don't have to modify the lower part of the script (past changing the dependencies folder path as needed), but in my case even after following the directions, I didn't have a compiled version of qmake, just sources. As a result, every time the script tried to build the qttools with qmake, it would fail because qmake.exe didn't exist.

So,  I modified the script to change line 50 from:

BUILD_QTBASE=0

to:

BUILD_QTBASE=1

Now I can see the qbase compilation trucking along (albeit slowly. my CPU is under 23% utilized and my disk is under 6% I/O saturation and memory is holding around 5.0gb of 8gb, so I'm not sure what the hold-up is... Could just be the cost of the mingw32 environment itself playing "nice" with the host environment (Windows 10)?)

In any event, I thought you'd like to know the compile-dependencies script may not be suitable for everyone "out of the box"...

**Comment by JERisBRISK** [comment]
...and that also didn't work. tail of stdout is:

> mingw32-make[3]: Leaving directory 'c:/Dependencies/qttools-opensource-src-5.4.2/src/windeployqt'
> mingw32-make[2]: Leaving directory 'c:/Dependencies/qttools-opensource-src-5.4.2/src/windeployqt'
> cd qtdiag/ && ( test -e Makefile || c:/Dependencies/qtbase-opensource-src-5.4.2/bin/qmake.exe C:/Dependencies/qttools-opensource-src-5.4.2/src/qtdiag/qtdiag.pro -o Makefile ) && c:/Dependencies/mingw32/bin/mingw32-make -f Makefile
> Qt: Untested Windows version 10.0 detected!
> mingw32-make[2]: Entering directory 'c:/Dependencies/qttools-opensource-src-5.4.2/src/qtdiag'
> c:/Dependencies/mingw32/bin/mingw32-make -f Makefile.Release
> mingw32-make[3]: Entering directory 'c:/Dependencies/qttools-opensource-src-5.4.2/src/qtdiag'
> mingw32-make[3]: **\* No rule to make target 'C:/Dependencies/qtbase-opensource-src-5.4.2/lib/libQt5Gui.a', needed by 'C:/Dependencies/qtbase-opensource-src-5.4.2/bin/qtdiag.exe'.  Stop.
> mingw32-make[3]: Leaving directory 'c:/Dependencies/qttools-opensource-src-5.4.2/src/qtdiag'
> Makefile:34: recipe for target 'release' failed
> mingw32-make[2]: **\* [release] Error 2
> mingw32-make[2]: Leaving directory 'c:/Dependencies/qttools-opensource-src-5.4.2/src/qtdiag'
> Makefile:116: recipe for target 'sub-qtdiag-make_first' failed
> mingw32-make[1]: **\* [sub-qtdiag-make_first] Error 2
> mingw32-make[1]: Leaving directory 'c:/Dependencies/qttools-opensource-src-5.4.2/src'
> makefile:40: recipe for target 'sub-src-make_first' failed
> mingw32-make: **\* [sub-src-make_first] Error 2

So i've enabled building _everything_ to make sure all the dependencies will indeed build...

**Comment by arcanis** [comment]
Thanks, it was a mistake ! All BUILD_XXXX variables should indeed have been enabled. I probably forgot to revert my changes after testing :)

**Comment by arcanis** [comment]
> Now I can see the qbase compilation trucking along (albeit slowly. my CPU is under 23% utilized and my disk is under 6% I/O saturation and memory is holding around 5.0gb of 8gb, so I'm not sure what the hold-up is... Could just be the cost of the mingw32 environment itself playing "nice" with the host environment (Windows 10)?)

Yeah, Windows take an awful lot of time to compile. That being said, Qt & Boost are monsters by themselves, so it's not that big of a surprise (it's faster on Linux / OSX because the packages have been pre-built by their maintainers)

**Comment by JERisBRISK** [comment]
Well, sadly my full build still didn't fly.

I'm not a bash/ming expert - are their build logs created anywhere that i could upload, or do i need to pipe the output to a file somehow?

**Comment by arcanis** [comment]
I think you should be able to pipe the output into a file, with something like this:

```
$> ../path/to/build-dependencies.sh > ./debug.log
```

Which should give you a `debug.log` file. At least I hope so. Worst case scenario, the log tail should be enough to give us a bit more informations about what is failing.

**Comment by JERisBRISK** [comment]
Ok. Well, i kicked off another full build and am piping out to a build.log which I'll share when it's done. Probably take an hour or more, and I have meetings, so perhaps this afternoon (PST) I can post it. 

Speaking of posting, i don't see a handy way of attaching files here. Recommendation? ;-)

**Comment by arcanis** [comment]
For a command-line addict like me, [Sprunge](http://sprunge.us/) is the bomb. Otherwise, maybe just [gist](https://gist.github.com/), depending on the filesize.

**Comment by JERisBRISK** [comment]
Saw a warning pop out to stdout and realized i needed to pipe stderr out as well. Some bing searching led me to the *nix equivalent of what I'm used to with windows:

> $ ./compile-dependencies.sh **&**> build.log

I'll probably use gist. Sprunge looks neat, but I honestly don't want to take the time to figure it out (or to restart my build ... I suppose i could just cat the file into sprunge or something, but I'm clueless about the right syntax or how to find it when it's done. =^)

**Comment by JERisBRISK** [comment]
here you go: https://gist.github.com/aviolentgrace/0e5aafd3c126c0eae622

**Comment by arcanis** [comment]
There's apparently an issue with the libpng library:

```
In file included from image/qpnghandler.cpp:50:0:
c:/Dependencies/libpng/libpng-1618/png.h:480:27: fatal error: pnglibconf.h: No such file or directory
 #   include "pnglibconf.h"
                           ^
compilation terminated.
Makefile.Release:29490: recipe for target '.obj/release/qpnghandler.o' failed
```

Apparently the libpng compilation failed because of this (you probably used a newer version than us, where they appear to have broken the way the library was compiled until now):

```

  There is no "configure" script in this distribution (*.zip or *.7z) of
  libpng-1.6.18.

  Instead, please copy the appropriate makefile for your system from the
  "scripts" directory.  Read the INSTALL file for more details.

  Update, July 2004: you can get a "configure" based distribution
  from the libpng distribution sites.  Download the file
  libpng-1.6.18.tar.gz or libpng-1.6.18.tar.xz.

  If the line endings in the files look funny, which is likely to be the
  case if you were trying to run "configure" on a Linux machine, you may
  wish to get the other distribution of libpng.  It is available in both
  tar.gz/tar.xz (UNIX style line endings, with "configure") and .7z/.zip
  (DOS style line endings, without "configure") formats.

make: *** No targets specified and no makefile found.  Stop.
ls: /c/Dependencies//./libpng/libpng-1618//.libs/libpng.a: No such file or directory
```
