### ISSUE TITLE
r1.1.0 UI - about the "?" link (Staking)

### ISSUE THREAD

**Issue by Moh-Said** [NeuCoin/neucoin#23]
Hello,
I just downloaded the new release (_1.1.0_).
I have two points to report :
**1-** When clicking on the "?" (Estimated stake time), nothing hapens, no links opens.
**2-** The url you set is incorrect (I checked the source), you set then url to the dev-branch !

Thank you.

**Comment by arcanis** [comment]
Fixed by 5fbfe5b5f4c6aac99b2177f4796b30b0af2f6a35, thanks ! :)
