### ISSUE TITLE
can't send text message

### ISSUE THREAD

**Issue by hennoxlane** [NeuCoin/neucoin#24]
I'm trying to verify my account, and am entering my (correct) phone number (+32 prefix, Belgium). 
However, I'm always getting the message "unable to send text message".

Tried in chrome & safari.

**Comment by arcanis** [comment]
Hi hennoxlane,

The team in charge of the Qt client and the team in charge of MyNeucoin are not the same, and they are unlikely to see any issue posted here. I suggest you to use the forum and/or to mail them at help@neucoin.org.

That being said, they are aware of the issue.
