### ISSUE TITLE
Only Whole Amounts Into Growth Account

### ISSUE THREAD

**Issue by Copenman** [NeuCoin/neucoin#3]
Received an error stating "Please enter a whole number (without decimals)", when attempting to add a second transaction to my growth account.

![accounts myneucoin](https://cloud.githubusercontent.com/assets/14339230/9949119/cb44f836-5d5e-11e5-8afa-07cc7da975bd.png)

**Comment by Magicking** [comment]
Hi Copenman,

This is a place to report issues with the client, you should head back to http://forum.neucoin.org/ regarding you problem.

Regards,

**Comment by Copenman** [comment]
Ok there's some miscommunication occurring, as when posting in the forum I'm being directed to post here and you're say post there lol

**Comment by Magicking** [comment]
You are showing a screenshot of the web wallet which is not the client and since I can't answer to your question, I'm referring you to the forum. Is that clearer ?
