### ISSUE TITLE
rescan needed before coldminting works

### ISSUE THREAD

**Issue by redfish64** [NeuCoin/neucoin#4]
I attempted to perform coldminting, as described in faq.md. However, until I rescanned the wallet on the server (the cold minter) side, it wouldn't start minting.

By rescan, I mean I added "rescan=1" to neucoin.conf

**Comment by arcanis** [comment]
Oh? That's strange, we actually have a functional test of this feature ([here](https://github.com/NeuCoin/neucoin/blob/master/test/test-cold-minting.js)), and it doesn't suffer the issue you described, according to Travis. Have you tried running it? You can find instructions [here](https://github.com/NeuCoin/neucoin/tree/master/test).

**Comment by Magicking** [comment]
I guess the issue referenced here is this one https://github.com/NeuCoin/neucoin/commit/8f8a3d16eb235f86ba531988cdeed9f403848f4d
Fixed by this one https://github.com/NeuCoin/neucoin/commit/d526ff50aebd3b13653948f2436832864639e0b1

**Comment by redfish64** [comment]
Yup, that fixed it. Thanks.
