### ISSUE TITLE
Problem with minting on client

### ISSUE THREAD

**Issue by shday** [NeuCoin/neucoin#5]
The GUI on my client always shows stake=0. I have waited over 1.6 days and my wallet is "Encrypted and currently unlocked for block minting only". (Though it wasn't unlocked the whole time... does that matter?)

I am using Ubuntu 15.04 and installed using the binary neucoin-qt_0.8.0.dfsg-1_amd64-ubuntu.deb

Screenshot and `listunspent` output below.

![nostake](https://cloud.githubusercontent.com/assets/335644/9981203/2d326e94-5f84-11e5-8d6d-eaa8ec4c8e44.png)

``` javascript

listunspent
[
{
"txid" : "309e5cdefd32f6edc9e9ae867a42657b6d6a9b5472fc3d8c33777091f5bb9b56",
"vout" : 0,
"address" : "NSKX9eQaTmLuPfivqSACzKRy9WkZNCNQwc",
"scriptPubKey" : "76a914464500f3000b148abdf357fe9498b5873f484de288ac",
"amount" : 489.99000000,
"confirmations" : 1233
},
{
"txid" : "a7ea0f9b91f40e7c1b789dd6fd2f0d8dce8cbb6979ddfff2357e5f4dccb2f194",
"vout" : 0,
"address" : "Nc73ui333zVZCSRhuKujfu9gMAFpDQ7TH3",
"scriptPubKey" : "76a914b19a87ec19604ee1d4f5fe72a66badf510a3424388ac",
"amount" : 94.99000000,
"confirmations" : 1220
},
{
"txid" : "b19e4e1853e4f3e8b3e82370460fade07ec6cd96ced81dafc78c231122cde2f8",
"vout" : 0,
"address" : "nBL428DfBdhLKYZegLu6kmnL8RdHncKPR3",
"account" : "cold minting address",
"scriptPubKey" : "a9144703fa2baa7e104e9e21337fff50fc116487c9d287",
"amount" : 5000.00000000,
"confirmations" : 3789
},
{
"txid" : "cf2fe444bfad97a3f35c02304ac3e53d8c1a101afb740fb214ba4a6e3a45112d",
"vout" : 0,
"address" : "NZGUxLqYb7E3vhwch1M4rAAwDhm4LrV6uQ",
"scriptPubKey" : "76a914927acdda9e32410bb7e845dba9f35d8391abfd7188ac",
"amount" : 387.46000000,
"confirmations" : 1232
},
{
"txid" : "d896b9923a1e89a9d0699f2953daac2323f13ad3f5c3cd56ebe75a0099d7219c",
"vout" : 0,
"address" : "NjD5oMepaY61ixbPjUdQYPCkJAH4dPrFfe",
"account" : "Default address",
"scriptPubKey" : "76a914ff877c3d184cbba9f2a1836596f6adf3ce37280888ac",
"amount" : 4005.00000000,
"confirmations" : 2643
}
]

```

**Comment by Magicking** [comment]
Waiting 1.6 days doesn't make it to automatically generate valid PoS block.

Is that the issue ?

**Comment by shday** [comment]
My understanding is that PoS should be automatic, as long as the wallet is unlocked. So far, my stake continues to show 0 in the GUI... so I take that to mean I'm not mining.

I think the issue is that PoS isn't starting automatically. Although it could just be a problem with the GUI. I'm afraid I don't know enough to tell the difference. e.g., I don't know how to tell if I've generated a valid PoS block (or even what that means).

Perhaps `getmininginfo` output would be useful:

``` javascript
{
"blocks" : 48404,
"currentblocksize" : 1000,
"currentblocktx" : 0,
"difficulty" : 0.00024414,
"errors" : "Warning: No sync-checkpoint received for quite a long time.",
"generate" : false,
"genproclimit" : -1,
"hashespersec" : 0,
"networkghps" : 0.00000027,
"pooledtx" : 0
}
```

**Comment by Magicking** [comment]
By default both the GUI and CLI version do the minting, you can double-check it by checking a line with this wording « CPUMiner started for proof-of-stake » in the file debug.log (located in the folder ~/.neucoin/)

**Comment by arcanis** [comment]
Nothing says that after 1.6 days you will mint. The thing is, 1.6 days is the minimal amount of time required for an utxo to start minting. Before that, it won't be able to mint at all. Then, once this treshold is reached, you will have to wait for the client to actually find a stake (finding a stake means that the utxo has produced a pseudo-random number low enough to match the network target).

A couple of notes:
- The network target depends on the network difficulty (actually, it's the exact same thing, in two different notations). So the more people stake, the more difficult it is to mint a PoS block.
- The PoS reward takes your coins age into account when minting. So it doesn't matter if you mint now or in ten days (except for compound interests) - you will still have the same reward for the time spent staking.

**Comment by shday** [comment]
Thanks for the clarifications.

So it looks like I am mining:

```
...-ThinkPad-X130e:~/.neucoin$ grep  proof debug.log 
2015-09-17 01:44:01 UTC CPUMiner started for proof-of-stake
2015-09-17 11:52:10 UTC CPUMiner started for proof-of-stake
2015-09-17 12:05:10 UTC CPUMiner started for proof-of-stake
2015-09-17 14:34:57 UTC CPUMiner started for proof-of-stake
2015-09-18 11:18:24 UTC CPUMiner started for proof-of-stake
2015-09-18 12:08:04 UTC CPUMiner started for proof-of-stake
2015-09-20 03:22:23 UTC CPUMiner started for proof-of-stake
```

So now my question is, what does the value of "Stake" (in my screenshot) actually represent?

**Comment by arcanis** [comment]
It shows the amount of stake rewards you've earned until now. It being at zero means that you haven't minted any block yet - you will need to wait more.

**Comment by shday** [comment]
Okay, fine. I thought it was supposed to show how many coins were past 1.6 days and "Staking" (i.e., you are online). Perhaps "Stake Reward" or "Coins Minted" would be better wording?

I think you can close this ticket.
