### ISSUE TITLE
Confusion about the flowing

### ISSUE THREAD

**Issue by dieterdp2** [NeuCoin/neucoin#6]
I have installed the wallet v0.8.0-beta-beta for ubuntu. All functioned one smoothly.
But the status below on the left shows always a warning. The alert shows up to date.
So I transfered 100 Neu from my Onlinewallet to the wallet, which arrived in seconds.
Now the Last Transaction shows +4913.99 (which was the  Available Balance from my
Online Wallet after transfer the 100 NEU).
Only the Balance shows the correct 100 NEU......
Excuse for mine bad english. I hope it is clear.
![bildschirmfoto vom 2015-09-21 17 24 03](https://cloud.githubusercontent.com/assets/14584821/9996692/77d62148-6088-11e5-9a29-4c3bd731f7ea.png)

**Comment by arcanis** [comment]
Hi @dieterdp2,

> But the status below on the left shows always a warning. The alert shows up to date.

That's not an issue; the client is just saying that no sync-checkpoint has been emitted by the master clients yet. It will still work as expected.

> So I transfered 100 Neu from my Onlinewallet to the wallet, which arrived in seconds.
> Now the Last Transaction shows +4913.99 (which was the Available Balance from my
> Online Wallet after transfer the 100 NEU).

That's a problem that has already been solved in f890d25 and will be deployed in the next release. Thanks for your report nonetheless !

I'll close this issue for the time being, but feel free to comment if you have any trouble.
