### ISSUE TITLE
Windows QT Client - GetBlockHash => GENESIS HASH

### ISSUE THREAD

**Issue by mb2140** [NeuCoin/neucoin#7]
Keep getting an error running the new windows QT client:

kernel.cpp Line 341

pindex -> pprev || pindex > GetBlockHash() == GENSIS_HASH

**Comment by arcanis** [comment]
Hi!

Yep, you have to trash your old data - we switched to a fresh new Genesis & blockchain, now that we're out of beta!

On windows, you will want to remove this directory before starting the client (make a backup somewhere first, even if we're probably never going back :):

```
C:\Users\<User>\AppData\Roaming\NeuCoin
```

I'll make a post on the forum about this.

_edit: [here it is!](http://forum.neucoin.org/t/end-of-the-beta-remove-your-old-datadir/1582)_
